packages:
  - "wavedance"
  - "apps/*"
packageExtensions:
  react-remove-scroll@*:
    dependencies:
      tslib: ^2.8.1
  use-sidecar@*:
    dependencies:
      tslib: ^2.8.1
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  msw: true
  sharp: true
